<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-01T16:03:50 IST" name="Suite" finished-at="2023-03-01T16:05:06 IST" duration-ms="75648">
    <groups>
      <group name="Sanity">
        <method signature="OrderConfirmationPageTest.verifyOrderConfirmationByOrderDate(java.util.HashMap)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" name="verifyOrderConfirmationByOrderDate" class="com.dcpl.testcase.OrderConfirmationPageTest"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="OrderConfirmationPageTest.verifyOrderConfirmationByOrderDate(java.util.HashMap)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" name="verifyOrderConfirmationByOrderDate" class="com.dcpl.testcase.OrderConfirmationPageTest"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2023-03-01T16:03:50 IST" name="RegressionTest" finished-at="2023-03-01T16:05:06 IST" duration-ms="75648">
      <class name="com.dcpl.testcase.OrderConfirmationPageTest">
        <test-method is-config="true" signature="readConfig()[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:03:49 IST" name="readConfig" finished-at="2023-03-01T16:03:50 IST" duration-ms="805" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readConfig -->
        <test-method is-config="true" signature="setUP(java.lang.String)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:03:53 IST" name="setUP" finished-at="2023-03-01T16:04:03 IST" duration-ms="9918" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method retried="true" signature="verifyOrderConfirmationByOrderDate(java.util.HashMap)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:04:03 IST" name="verifyOrderConfirmationByOrderDate" description="Verifying order confirmation by passing from and to date" data-provider="OrderConfirmationPageData" finished-at="2023-03-01T16:04:13 IST" duration-ms="10030" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{fromday=15, password=Pass@123, orderno=, frommonth=Feb, tomonth=Feb, salesexecutive=Hashmi, fromyear=2023, today=28, hrms_id=15, toyear=2023}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Order Confirm Cashier - Sales] but found [Sales - Dashboard - Sales]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Order Confirm Cashier - Sales] but found [Sales - Dashboard - Sales]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.dcpl.testcase.OrderConfirmationPageTest.verifyOrderConfirmationByOrderDate(OrderConfirmationPageTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderConfirmationByOrderDate -->
        <test-method is-config="true" signature="closeWebApplication()[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:04:13 IST" name="closeWebApplication" finished-at="2023-03-01T16:04:20 IST" duration-ms="6279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWebApplication -->
        <test-method is-config="true" signature="setUP(java.lang.String)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:04:20 IST" name="setUP" finished-at="2023-03-01T16:04:27 IST" duration-ms="7533" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method retried="true" signature="verifyOrderConfirmationByOrderDate(java.util.HashMap)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:04:27 IST" name="verifyOrderConfirmationByOrderDate" description="Verifying order confirmation by passing from and to date" data-provider="OrderConfirmationPageData" finished-at="2023-03-01T16:04:37 IST" duration-ms="9922" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{fromday=15, password=Pass@123, orderno=, frommonth=Feb, tomonth=Feb, salesexecutive=Hashmi, fromyear=2023, today=28, hrms_id=15, toyear=2023}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Order Confirm Cashier - Sales] but found [Sales - Dashboard - Sales]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Order Confirm Cashier - Sales] but found [Sales - Dashboard - Sales]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.dcpl.testcase.OrderConfirmationPageTest.verifyOrderConfirmationByOrderDate(OrderConfirmationPageTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderConfirmationByOrderDate -->
        <test-method is-config="true" signature="closeWebApplication()[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:04:37 IST" name="closeWebApplication" finished-at="2023-03-01T16:04:43 IST" duration-ms="6189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWebApplication -->
        <test-method is-config="true" signature="setUP(java.lang.String)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:04:44 IST" name="setUP" finished-at="2023-03-01T16:04:49 IST" duration-ms="5245" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="verifyOrderConfirmationByOrderDate(java.util.HashMap)[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:04:49 IST" name="verifyOrderConfirmationByOrderDate" description="Verifying order confirmation by passing from and to date" data-provider="OrderConfirmationPageData" finished-at="2023-03-01T16:04:59 IST" duration-ms="10086" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{fromday=15, password=Pass@123, orderno=, frommonth=Feb, tomonth=Feb, salesexecutive=Hashmi, fromyear=2023, today=28, hrms_id=15, toyear=2023}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Order Confirm Cashier - Sales] but found [Sales - Dashboard - Sales]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Order Confirm Cashier - Sales] but found [Sales - Dashboard - Sales]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.dcpl.testcase.OrderConfirmationPageTest.verifyOrderConfirmationByOrderDate(OrderConfirmationPageTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderConfirmationByOrderDate -->
        <test-method is-config="true" signature="closeWebApplication()[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:05:00 IST" name="closeWebApplication" finished-at="2023-03-01T16:05:06 IST" duration-ms="5868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWebApplication -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.dcpl.testcase.OrderConfirmationPageTest@2892d68]" started-at="2023-03-01T16:05:06 IST" name="afterSuite" finished-at="2023-03-01T16:05:07 IST" duration-ms="1242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.dcpl.testcase.OrderConfirmationPageTest -->
    </test> <!-- RegressionTest -->
  </suite> <!-- Suite -->
</testng-results>
