<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP" ignored="0" name="RegressionTest(failed)(failed)(failed)(failed)" tests="1" failures="1" timestamp="2023-01-30T11:50:17 IST" time="35.354" errors="0">
  <testcase name="verifyingOrderConfirmationByStoreHead" time="15.382" classname="com.dcpl.testcase.StoreHeadConfirmationPageTest">
    <failure type="java.lang.AssertionError" message="expected [1 are confirmed SuccessFully] but found [1 are successfully confirmed]">
      <![CDATA[java.lang.AssertionError: expected [1 are confirmed SuccessFully] but found [1 are successfully confirmed]
at com.dcpl.testcase.StoreHeadConfirmationPageTest.verifyingOrderConfirmationByStoreHead(StoreHeadConfirmationPageTest.java:58)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyingOrderConfirmationByStoreHead -->
</testsuite> <!-- RegressionTest(failed)(failed)(failed)(failed) -->
